* SectionsL

** Introduction
   Anyone can hack
   On the Internet, nobody knows you're a dog
   What about college?
   What's in this book?
   Bill Gates, Steve Jobs, and Elon Musk didn't
   How to teach yourself hacking, for $0
   How to read this book (and if you find something cool, set this down and come back to it)
   College is the easy route. This is faster, harder, and much more effective.
  
*** Homework
    The Hacker's Manifesto
    Bill Watterson's Commencement Speech
    Paul Graham Great Hackers 

*** Supplements
    Zen and the Art of Motorcycle Maintenance
    You're not Special
    The Matrix
    ? College: What is Was, Is, and Should Be

** Your first computer
   This is important and necessary
   Buying a computer
*** Homework
    Buy a computer.n Or dig one out of the dumpster and fix it

** Linux
   Installing linux

** The Command Line [intro to Linux]
** Vim
** More Command line [intro to bash scripting]
** More Command line [tmux]
   
** Git

** C & GCC

** FOSS
*** Pentadactyl
    With curl plugin
*** Mutt
*** AnkiDroid
*** VLC
*** AntennaPod

*** Homework
    "The Cathedral and the Bazaar"

** A Moment of zen
   Talk about principles
*** Homework
    The Pragmatic Programmer [if open source]
    The Art of Unix Programming
    The Unix Hater's Handbook [if open source]
    The Mythical Man Month [if open source]
** Emacs

** Lisp

** Data Structures and Algorithms
   Open Data Structures [read this and check that it's good]

** Command Line text processing tools
   Sed
   Awk
   cut

** Python

** Markdown
*** Homework
    "Learn Markdown" [check that this is good]
    https://www.gitbook.com/book/gitbookio/markdown/details
*** Homework
    "Open Advice" book

** zsh

** Math

** Data Structures and Algorithms

** Haskell

** Business & Economics

** Other People
*** Homework
    How to Win Friends and Influence People
    Truth in Comedy
    Zen and the Art of Writing

** Startups

** Java

** Intro Web Development: HTML, CSS, JQuery, JavaScript
*** Homework
    Codecademy

** Basic SQL

* Whatever order you 

** Advanced Mathematics

** Android

** Django Servers

** Advanced Web Development

** R, Machine Learning, and Artificial Intelligence

** Arduino

** Electrical Engineering

** Raspberry PI

** Security

** LaTeX

** Contributing back to FOSS
   You think you know a lot. Try contributing back by writing an open source textbook, or to open source software

* Maybe add

** Robotics

** Perl

** Ruby

** Windows

** Apple
   
* Structure
  Each chapter has

** Homework
   Mandatory
   Put all XKCD comics here.

** Supplementary exercises
   Suggested, if you can afford them

** Side Quests
   Strictly Optional
